name: exam_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # DI
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Network
  retrofit: ^4.9.0
  dio: ^5.9.2

  # State Management
  flutter_bloc: ^9.1.1

  # Serialization
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^10.0.0

  # UI
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.2
  fluttertoast: ^9.0.0
  cupertino_icons: ^1.0.8

  # Utils
  logger: ^2.6.0
  pinput: ^6.0.2
  lottie: ^3.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/examlogo.png"

  # Android 8+
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/icons/examlogo.png"